name: Integration tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        php: [ '7.3', '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Install Composer Vendor Plugin
        run: composer global require liborm85/composer-vendor-cleaner

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Files list
        run: find . -print